spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MyLinux123
    url: jdbc:mysql://123.56.152.3:3306/back_office?characterEncoding=utf-8&useSSL=false
  redis:
    host: 123.56.152.3
    port: 6379
    timeout: 2000s
  rabbitmq:
    addresses: 123.56.152.3
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  port: 9002
#  servlet:
#    session:
#      timeout: 120

