server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        #- id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
         # uri: lb://cloud-payment-service
        #  predicates:
            #- Path=/payment/getPaymentById/** # 断言，路径相匹配的进行路由

        #- id: payment_route2
          #uri: http://localhost:8001
          #uri: lb://cloud-payment-service
         # predicates:
            #- Path=/payment/lb/** #断言,路径相匹配的进行路由
         #   - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
          #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/

#spring:
#  cloud:
##################################
##   gateway相关配置
##################################
#    gateway:
#      ################################
#      # 配置允许跨域请求
#      ################################
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#            - POST
##    路由定义
#      routes:
#
#      - id: baidu
#        uri: https://www.baidu.com
#        predicates:
#        - Path=/baidu/**
#        filters:
#        - StripPrefix=1
#
#      - id: eureka-manage
#        uri: lb://eureka-manage
#        predicates:
#        - Path=/eureka-manage/**
#        filters:
#        - StripPrefix=1
#
#      - id: sina
#        uri: https://www.sina.com.cn/
#        predicates:
#        - Path=/sina/**
#        filters:
#        - StripPrefix=1
#
org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
#      - /baidu
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1m